#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
    # Write your code here
    def digit_sum(num):
        if len(num)== 1:
            return num[0]
        collector = 0
        for i in range(len(num)):
            collector += int(num[i])
        num = digit_sum((str(collector)))
        return num
    first_round = 0
    for num in n:
        first_round += int(num)
    return digit_sum(str(first_round) * k)
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()
